# Generated by Django 4.2 on 2023-04-28 13:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_rename_title_route_route_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_location',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
