# Generated by Django 4.2 on 2023-05-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_route_description_alter_route_start_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0003_ride_ride_date_ride_start_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ride',
            options={'ordering': ['-ride_date']},
        ),
        migrations.AddField(
            model_name='ride',
            name='participants',
            field=models.ManyToManyField(related_name='ride_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.route'),
        ),
    ]
