# Generated by Django 4.2 on 2023-05-11 23:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_ride_report_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='ride_report_text',
            field=ckeditor.fields.RichTextField(default=' '),
            preserve_default=False,
        ),
    ]
