# Generated by Django 4.2 on 2023-05-14 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_alter_ride_ride_report_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='pictures/')),
                ('caption', models.CharField(max_length=512)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_pictures', to='rides.ride')),
            ],
        ),
    ]
